/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject1;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.ButtonGroup;

/**
 *
 * @author OWNER
 */
public class id_question10 extends javax.swing.JFrame
{

    /**
     * Creates new form id_question10
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement stmt;
    String value;
    
    public id_question10()
    {
        setTitle("Now Playing... QUIZ");
        initComponents();
        
        showscore();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_question10 = new javax.swing.JLabel();
        a10_id = new javax.swing.JRadioButton();
        c10_id = new javax.swing.JRadioButton();
        b10_id = new javax.swing.JRadioButton();
        d10_id = new javax.swing.JRadioButton();
        answer_button = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        scorebox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id_question10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        id_question10.setText("What is Ms. Monica Hidajat's Binus ID number?");

        a10_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        a10_id.setText("D4954");
        a10_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10_idActionPerformed(evt);
            }
        });

        c10_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c10_id.setText("D3797");
        c10_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10_idActionPerformed(evt);
            }
        });

        b10_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b10_id.setText("D3779");
        b10_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10_idActionPerformed(evt);
            }
        });

        d10_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        d10_id.setText("D4854");
        d10_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10_idActionPerformed(evt);
            }
        });

        answer_button.setText("Finish!");
        answer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_buttonActionPerformed(evt);
            }
        });

        progressBar.setValue(90); progressBar.setVisible(true);

        scorebox.setText("SCORE: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scorebox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(id_question10)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a10_id)
                    .addComponent(c10_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b10_id)
                    .addComponent(d10_id))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scorebox)
                .addGap(37, 37, 37)
                .addComponent(id_question10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a10_id)
                    .addComponent(b10_id))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c10_id)
                    .addComponent(d10_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(answer_button)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton()
    {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(a10_id);
        bg2.add(b10_id);
        bg2.add(c10_id);
        bg2.add(d10_id);
    }
    
    public void showscore()
    {
        scoreboard scr = new scoreboard();
        scorebox.setText("Score: " + scr.getScore());
    }
    
    private void a10_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10_idActionPerformed
        // TODO add your handling code here:
        value = "D4954";
    }//GEN-LAST:event_a10_idActionPerformed

    private void c10_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10_idActionPerformed
        // TODO add your handling code here:
        value = "D3797";
    }//GEN-LAST:event_c10_idActionPerformed

    private void b10_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10_idActionPerformed
        // TODO add your handling code here:
        value = "D3779";
    }//GEN-LAST:event_b10_idActionPerformed

    private void d10_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10_idActionPerformed
        // TODO add your handling code here:
        value = "D4854";
    }//GEN-LAST:event_d10_idActionPerformed

    private void answer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_buttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String submittedQuery = "INSERT INTO inputted_answers(ans) VALUES (?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            pst = conn.prepareStatement(submittedQuery);
            pst.setString(1, value);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Are you sure?");
            String extractQuery= "SELECT inputted_answers.ans, idn_answers.ans FROM idn_answers INNER JOIN (SELECT ans FROM inputted_answers order by id desc limit 1) as inputted_answers on inputted_answers.ans = idn_answers.ans";
            pst = conn.prepareStatement(extractQuery);

            rs = pst.executeQuery();
            if(rs.next())
            {
                String valueQuery = "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Correct!");
                pst.executeUpdate();
            }
            else
            {
                String valueQuery= "INSERT INTO comparison(value) VALUES (?)";
                pst=conn.prepareStatement(valueQuery);
                pst.setString(1, "Incorrect");
                pst.executeUpdate();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Whoops! Check your connection!");
        }

        checkanswer();
        
        finish_menu q = new finish_menu();
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_answer_buttonActionPerformed

    private void checkanswer()
    {
        if("D4954".equals(value))
            { 
                scoreboard scr = new scoreboard();
                scr.addScore();
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(id_question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(id_question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(id_question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(id_question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new id_question10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a10_id;
    private javax.swing.JButton answer_button;
    private javax.swing.JRadioButton b10_id;
    private javax.swing.JRadioButton c10_id;
    private javax.swing.JRadioButton d10_id;
    private javax.swing.JLabel id_question10;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel scorebox;
    // End of variables declaration//GEN-END:variables
}
