/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject1;

import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author OWNER
 */
public class question10 extends javax.swing.JFrame
{

    /**
     * Creates new form question10
     */
    String value;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement stmt;
    
    public question10()
    {
        setTitle("Now Playing... QUIZ");
        initComponents();
        showscore();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        question10 = new javax.swing.JLabel();
        A10 = new javax.swing.JRadioButton();
        C10 = new javax.swing.JRadioButton();
        D10 = new javax.swing.JRadioButton();
        B10 = new javax.swing.JRadioButton();
        answer_button = new javax.swing.JButton();
        scorebox = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        progressBar.setValue(90);
        progressBar.setVisible(true);

        question10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        question10.setText("How many questions does this quiz have?");

        A10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A10.setText("9");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });

        C10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C10.setText("10");
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });

        D10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D10.setText("I don't know");
        D10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D10ActionPerformed(evt);
            }
        });

        B10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B10.setText("12");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        answer_button.setText("FINISH");
        answer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_buttonActionPerformed(evt);
            }
        });

        scorebox.setText("SCORE: ");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C10)
                            .addComponent(A10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D10)
                            .addComponent(B10))
                        .addGap(81, 81, 81))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scorebox)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(594, Short.MAX_VALUE)
                    .addComponent(answer_button)
                    .addGap(57, 57, 57)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scorebox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(question10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A10)
                    .addComponent(B10))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C10)
                    .addComponent(D10))
                .addGap(171, 171, 171))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(405, Short.MAX_VALUE)
                    .addComponent(answer_button)
                    .addGap(61, 61, 61)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton()
    {
        ButtonGroup bg2 = new ButtonGroup();

        bg2.add(A10);
        bg2.add(B10);
        bg2.add(C10);
        bg2.add(D10);
    }
    
    public void showscore()
    {
        scoreboard scr = new scoreboard();
        scorebox.setText("Score: " + scr.getScore());
    }
    
    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
        // TODO add your handling code here:
        value = "9";
    }//GEN-LAST:event_A10ActionPerformed

    private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
        // TODO add your handling code here:
        value = "10";
    }//GEN-LAST:event_C10ActionPerformed

    private void D10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D10ActionPerformed
        // TODO add your handling code here:
        value = "I don't know";
    }//GEN-LAST:event_D10ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:
        value = "12";
    }//GEN-LAST:event_B10ActionPerformed

    public void checkanswer()
    {
        if("10".equals(value))
            {
                scoreboard scr = new scoreboard();
                scr.addScore();
            }
    }
    
    // performs the action when the ANSWER/SUBMIT button is clicked or selected
    private void answer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_buttonActionPerformed
        // TODO add your handling code here:
        try
        {
            String submittedQuery = "INSERT INTO inputted_answers(ans) VALUES (?)";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            pst = conn.prepareStatement(submittedQuery);
            pst.setString(1, value);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Are you sure?");
            String extractQuery= "SELECT inputted_answers.ans, answers.ans FROM answers INNER JOIN (SELECT ans FROM inputted_answers order by id desc limit 1) as inputted_answers on inputted_answers.ans = answers.ans";
            pst = conn.prepareStatement(extractQuery);

            rs = pst.executeQuery();
            if(rs.next())
            {
                String valueQuery = "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Correct!");
                pst.executeUpdate();
            }
            else
            {
                String valueQuery= "INSERT INTO comparison(value) VALUES (?)";
                pst=conn.prepareStatement(valueQuery);
                pst.setString(1, "Incorrect");
                pst.executeUpdate();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Hang on!");
        }
        checkanswer();
        finish_menu q = new finish_menu();
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_answer_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new question10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A10;
    private javax.swing.JRadioButton B10;
    private javax.swing.JRadioButton C10;
    private javax.swing.JRadioButton D10;
    private javax.swing.JButton answer_button;
    private javax.swing.JMenuBar jMenuBar1;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel question10;
    private javax.swing.JLabel scorebox;
    // End of variables declaration//GEN-END:variables
}
