/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject1;

import jaco.mp3.player.MP3Player;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author OWNER
 */
public class id_question1 extends mainmenu//javax.swing.JFrame
{

    /**
     * Creates new form id_question1
     */
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement stmt;
    String value;
    
    public id_question1()
    {
        setTitle("Now Playing... QUIZ");
        initComponents();
        resetcomparison();
        resetinput();
        resetscore();
        showscore();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        id_question1 = new javax.swing.JLabel();
        a1_id = new javax.swing.JRadioButton();
        b1_id = new javax.swing.JRadioButton();
        c1_id = new javax.swing.JRadioButton();
        d1_id = new javax.swing.JRadioButton();
        answer_button = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        scorebox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        id_question1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        id_question1.setText("Whicih of these folklores are NOT from Java?");

        a1_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        a1_id.setText("Tangkuban Parahu");
        a1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1_idActionPerformed(evt);
            }
        });

        b1_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b1_id.setText("Si Pitung");
        b1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1_idActionPerformed(evt);
            }
        });

        c1_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c1_id.setText("Nyi Roro Kidul");
        c1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1_idActionPerformed(evt);
            }
        });

        d1_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        d1_id.setText("Malin Kundang");
        d1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1_idActionPerformed(evt);
            }
        });

        answer_button.setText("Submit");
        answer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_buttonActionPerformed(evt);
            }
        });

        progressBar.setValue(0); progressBar.setVisible(true);

        scorebox.setText("SCORE: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_question1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a1_id)
                            .addComponent(c1_id))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1_id)
                            .addComponent(d1_id))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scorebox)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scorebox)
                .addGap(39, 39, 39)
                .addComponent(id_question1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1_id)
                    .addComponent(b1_id))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1_id)
                    .addComponent(d1_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(answer_button)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void groupButton()
    {
        ButtonGroup bg2 = new ButtonGroup();
        
        bg2.add(a1_id);
        bg2.add(b1_id);
        bg2.add(c1_id);
        bg2.add(d1_id);
    }
    
    public void resetscore()
    {
        scoreboard scr = new scoreboard();
        scr.reset();
    }
    
    public void resetinput()
    {
        String sql = "DELETE from inputted_answers";
        
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            stmt = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            System.err.print("\n[RESET INPUT] Whoops.. Somethings not right.. ");
        }
    }
    
    public void resetcomparison()
    {
        String sql = "DELETE from comparison";
        
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            stmt = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            System.err.print("\n[RESET COMPARISON] Whoops.. Somethings not right.. ");
        }
    }
    
    public void showscore()
    {
        scoreboard scr = new scoreboard();
        scorebox.setText("Score: " + scr.getScore());
    }
    
    public void playmusic()
    {
        MP3Player bgm;
        bgm = new MP3Player(new File("C:\\Users\\OWNER\\Documents\\NetBeansProjects\\FinalProject1\\src\\finalproject1\\bgm_2.mp3"));
        bgm.play();
    }
    
    private void a1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1_idActionPerformed
        // TODO add your handling code here:
        value = "Tangkuban Parahu";
    }//GEN-LAST:event_a1_idActionPerformed

    private void b1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1_idActionPerformed
        // TODO add your handling code here:
        value = "Si Pitung";
    }//GEN-LAST:event_b1_idActionPerformed

    private void c1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1_idActionPerformed
        // TODO add your handling code here:
        value = "Nyi Roro Kidul";
    }//GEN-LAST:event_c1_idActionPerformed

    private void d1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1_idActionPerformed
        // TODO add your handling code here:
        value = "Malin Kundang";
    }//GEN-LAST:event_d1_idActionPerformed

    private void checkanswer()
    {
        if("Malin Kundang".equals(value))
            { 
                scoreboard scr = new scoreboard();
                scr.addScore();
            }
    }
    
    private void answer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_buttonActionPerformed
        // TODO add your handling code here:
        try
        {
            //reset the data from the whole table
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            String reset = String.format("ALTER TABLE inputted_answers AUTO_INCREMENT = 1");
            stmt.execute(reset);
            String reset2 = "ALTER TABLE comparison AUTO_INCREMENT = 1";
            stmt.execute(reset2);
            String submittedQuery = "INSERT INTO inputted_answers(ans) VALUES (?)";
            
            pst = conn.prepareStatement(submittedQuery);
            pst.setString(1, value);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Are you sure?");
            String extractQuery= "SELECT inputted_answers.ans, idn_answers.ans FROM idn_answers INNER JOIN (SELECT ans FROM inputted_answers order by id desc limit 1) as inputted_answers on inputted_answers.ans = idn_answers.ans";
            pst = conn.prepareStatement(extractQuery);
            
            rs = pst.executeQuery();
            if(rs.next())
            {
                String valueQuery = "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Correct!");
                pst.executeUpdate();
            }
            else
            {
                String valueQuery= "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Incorrect");
                pst.executeUpdate();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Done!");
        }
        checkanswer();
        id_question2 q = new id_question2();
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_answer_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        playmusic();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(id_question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(id_question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(id_question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(id_question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new id_question1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1_id;
    private javax.swing.JButton answer_button;
    private javax.swing.JRadioButton b1_id;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c1_id;
    private javax.swing.JRadioButton d1_id;
    private javax.swing.JLabel id_question1;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel scorebox;
    // End of variables declaration//GEN-END:variables
}
