/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject1;
import java.io.File;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.Timer;
import jaco.mp3.player.MP3Player;
import java.text.SimpleDateFormat;
/**
 *
 * @author OWNER
 */
public class question1 extends javax.swing.JFrame
{

    /**
     * Creates new form question1
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement stmt;
    String value;
    int timeLeft = 15000;
    int count;
    Timer timer;
    
    public question1()
    {
        setTitle("Now Playing... QUIZ");
        initComponents();
        resetcomparison();
        resetinput();
        resetscore();
        showscore();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1 = new javax.swing.JLabel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        answer_button = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        scorebox = new javax.swing.JLabel();
        timer1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        question1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        question1.setText("Who invented the light bulb?");
        question1.setToolTipText("");

        A.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A.setText("Thomas Alva Edison");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        B.setText("Ferdinand Magellan");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        C.setText("Isaac Newton");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        D.setText("Benjamin Franklin");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        answer_button.setText("Submit");
        answer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_buttonActionPerformed(evt);
            }
        });

        progressBar.setValue(0);
        progressBar.setVisible(true);

        scorebox.setLabelFor(scorebox);
        scorebox.setText("SCORE: ");

        timer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timer1.setLabelFor(timer1);
        timer1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C)
                            .addComponent(A))
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B)
                            .addComponent(D))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(answer_button)
                .addGap(32, 32, 32))
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scorebox)
                .addGap(244, 244, 244)
                .addComponent(timer1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scorebox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(timer1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(D))
                .addGap(32, 32, 32)
                .addComponent(answer_button)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void groupButton()
    {
        ButtonGroup bg2 = new ButtonGroup();

        bg2.add(A);
        bg2.add(B);
        bg2.add(C);
        bg2.add(D);
    }
    
    public void resetscore()
    {
        scoreboard scr = new scoreboard();
        scr.reset();
    }
    
    public void resetinput()
    {
        String sql = "DELETE from inputted_answers";
        
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            stmt = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            System.err.print("\n[RESET INPUT] Whoops.. Somethings not right.. ");
        }
    }
    
    public void resetcomparison()
    {
        String sql = "DELETE from comparison";
        
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            stmt = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            System.err.print("\n[RESET COMPARISON] Whoops.. Somethings not right.. ");
        }
    }
    
    public void showscore()
    {
        scoreboard scr = new scoreboard();
        //scorebox.setText("Score: " + scr.getScore());
        System.out.println("welp" + scr.getScore());
        scr.getScore();
        System.out.println("welp2" + scr.getScore());
    }
    
    public void setTimer()
    {
        quiz_timer tmr = new quiz_timer();
        SimpleDateFormat df = new SimpleDateFormat("mm:ss");
        timer1.setText(df.format(timeLeft));
        tmr.setTimer();
        
    }
    
    public static void playmusic()
    {
        MP3Player bgm;
        bgm = new MP3Player(new File("C:\\Users\\OWNER\\Documents\\NetBeansProjects\\FinalProject1\\src\\finalproject1\\bgm_1.mp3"));
        bgm.play();
    }
    
    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        value = "Thomas Alva Edison";
    }//GEN-LAST:event_AActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        value = "Isaac Newton";
    }//GEN-LAST:event_CActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        value = "Ferdinand Magellan";
    }//GEN-LAST:event_BActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        value = "Benjamin Franklin";
    }//GEN-LAST:event_DActionPerformed

    private void checkanswer()
    {
        if("Thomas Alva Edison".equals(value))
            { 
                scoreboard scr = new scoreboard();
                scr.addScore();
            }
    }
    
    private void answer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_buttonActionPerformed
        // TODO add your handling code here:
        try
        {
            //reset the whole table pls
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/finalproject1", "root", "");
            String reset = String.format("ALTER TABLE inputted_answers AUTO_INCREMENT = 1");
            stmt.execute(reset);
            String reset2 = "ALTER TABLE comparison AUTO_INCREMENT = 1";
            stmt.execute(reset2);
            String submittedQuery = "INSERT INTO inputted_answers(ans) VALUES (?)";
            
            pst = conn.prepareStatement(submittedQuery);
            pst.setString(1, value);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Are you sure?");
            String extractQuery= "SELECT inputted_answers.ans, answers.ans FROM answers INNER JOIN (SELECT ans FROM inputted_answers order by id desc limit 1) as inputted_answers on inputted_answers.ans = answers.ans";
            pst = conn.prepareStatement(extractQuery);
            
            rs = pst.executeQuery();
            if(rs.next())
            {
                String valueQuery = "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Correct!");
                pst.executeUpdate();
            }
            else
            {
                String valueQuery= "INSERT INTO comparison(value) VALUES (?)";
                pst = conn.prepareStatement(valueQuery);
                pst.setString(1, "Incorrect");
                pst.executeUpdate();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Oh no! \nUnable to save your answer! Please check your connection!", ":: Warning! ::", JOptionPane.WARNING_MESSAGE);
        }
        checkanswer();
        question2 q = new question2();
        q.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_answer_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        playmusic();
        setTimer();
        //reference: www.jacomp3player.sourceforge.net/
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new question1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JButton answer_button;
    private static javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel scorebox;
    private javax.swing.JLabel timer1;
    // End of variables declaration//GEN-END:variables
}
